apiVersion: v1
kind: ReplicationController
metadata:
   name: mariadb-vessel
   namespace: vessels
spec:
  replicas: 1
  selector:
    service: mariadb-vessel
  template:
    metadata:
      labels:
        service: mariadb-vessel
    spec:
      nodeSelector:
        kubernetes.io/hostname: kube2
      containers:
        - image: "ansibleapp/nave-centos-mariadb-vessel:latest"
          name: main
          ports:
            - containerPort: 3306
              name: mariadb-1
            - containerPort: 4444
              name: sst
            - containerPort: 4567
              name: replication
            - containerPort: 4568
              name: ist
            - containerPort: 443
              name: kube
            - containerPort: 6443
              name: kube-1
          volumeMounts:
            - mountPath: /var/log/vessel
              name: vessel-persistent-storage
            - mountPath: /var/lib/vessel-shared
              name: vessel-shared-storage
      volumes:
        - name: vessel-persistent-storage
          persistentVolumeClaim:
            claimName: mariadb-vessel
        - name: vessel-shared-storage
          persistentVolumeClaim:
            claimName: vessel-shared
