---
apiVersion: v1
kind: Namespace
metadata:
  name: vessels
---
apiVersion: v1
kind: Service
metadata:
   name: mariadb-vessel
   labels:
     name: mariadb-vessel
   namespace: vessels
spec:
  ports:
    - port: 443
      name: kube
    - port: 6443
      name: kube-2
    - port: 3306
      name: mariadb-2
    - port: 4567
      name: mariadb-2-replication-tcp
    - port: 4567
      name: mariadb-2-replication-udp
      protocol: UDP
    - port: 4444
      name: mariadb-2-sst
    - port: 4568
      name: mariadb-2-ist
  selector:
    service: mariadb-vessel
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-vessel
  namespace: vessels
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /var/lib/nave/vessel-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-vessel
  namespace: vessels
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
