apiVersion: v1
kind: Service
metadata:
   name: mariadb-{{count}}
   namespace: vessels
spec:
  ports:
    - port: 3306
      name: mariadb-{{count}}
    - port: 4567
      name: mariadb-{{count}}-replication-tcp
    - port: 4567
      name: mariadb-{{count}}-replication-udp
      protocol: UDP
    - port: 4444
      name: mariadb-{{count}}-sst
    - port: 4568
      name: mariadb-{{count}}-ist
  selector:
    service: mariadb-{{count}}
