apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-{{count}}
  namespace: vessels
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /var/lib/nave/mariadb-{{count}}
